stages:
  - compile
  - test
  - deploy

compile:
  script: mvn compile

test:
  script: mvn test

deploy:
  script: 
    - export PORT=5000
    - mvn package
    - sh target/bin/simplewebapp &> /dev/null &
