stages:
  - compile
  - test
  - deploy

compile:
  stage: compile
  script: mvn compile

test:
  stage: test
  script: mvn test

deploy:
  stage: deploy
  script: 
    - export PORT=5000
    - mvn package
    - sh target/bin/simplewebapp &> /dev/null &
    - dpl --provider=heroku --app=rp218-simplewebapp --api-key=43b796c8-8edb-4469-8d21-9c727720367a

